import Head from 'next/head'
import { Fragment } from 'react'

export default function Home() {
  return (
    <Fragment>
      {/* <Head>
        <title>emr</title>
        <meta name="description" content="Generated by emr" />
      </Head> */}

      <main>
        hello!
      </main>
    </Fragment>
  )
}
